import os
import json

from llama_index.core.tools import FunctionTool, QueryEngineTool
from llama_index.core.vector_stores import SimpleVectorStore
from llama_index.readers.web import SimpleWebPageReader
from llama_index.readers.semanticscholar import SemanticScholarReader
from llama_index.tools.wikipedia import WikipediaToolSpec
from llama_index.tools.tavily_research import TavilyToolSpec
from llama_index.tools.duckduckgo import DuckDuckGoSearchToolSpec
from llama_index.core import VectorStoreIndex, StorageContext, load_index_from_storage
from llama_index.core import Settings
from llama_index.tools.code_interpreter import CodeInterpreterToolSpec, CodeInterpreter # Import CodeInterpreter
from huggingface_hub import HfFileSystem

# --- Hugging Face RAG Configuration ---
HF_DATASET_ID = "gm42/esi_simplevector"
HF_VECTOR_STORE_SUBDIR = "vector_store_data"

# Determine project root based on the script's location
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# Ensure API keys are set as environment variables
# os.environ["TAVILY_API_KEY"] = "YOUR_TAVILY_API_KEY"
# os.environ["GOOGLE_API_KEY"] = "YOUR_GOOGLE_API_KEY"

# Directory where files generated by code interpreter should be accessible by the UI
UI_ACCESSIBLE_WORKSPACE_RELATIVE = "./code_interpreter_ws"
UI_ACCESSIBLE_WORKSPACE = os.path.join(PROJECT_ROOT, UI_ACCESSIBLE_WORKSPACE_RELATIVE)
os.makedirs(UI_ACCESSIBLE_WORKSPACE, exist_ok=True)


# --- Individual Tool Initializations ---

def get_duckduckgo_tool():
    """Initializes the DuckDuckGo search tool."""
    try:
        return DuckDuckGoSearchToolSpec().to_tool_list()[0]
    except NameError:
        print("Error: DuckDuckGoSearchToolSpec not found. Trying DuckDuckGoToolSpec.")
        try:
            from llama_index.tools.duckduckgo import DuckDuckGoToolSpec
            return DuckDuckGoToolSpec().to_tool_list()[0]
        except Exception as e_fallback:
            print(f"Error initializing DuckDuckGo Tool (fallback failed): {e_fallback}")
            return None
    except Exception as e:
        print(f"Error initializing DuckDuckGo Tool: {e}")
        return None

def get_tavily_tool():
    """Initializes the Tavily search tool."""
    tavily_api_key = os.getenv("TAVILY_API_KEY")
    if not tavily_api_key:
        print("Warning: TAVILY_API_KEY not found in environment variables.")
        return None
    try:
        return TavilyToolSpec(api_key=tavily_api_key).to_tool_list()[0]
    except Exception as e:
        print(f"Error initializing Tavily Tool: {e}")
        return None

def get_wikipedia_tool():
    """Initializes the Wikipedia tool."""
    try:
        return WikipediaToolSpec().to_tool_list()[0]
    except Exception as e:
        print(f"Error initializing Wikipedia Tool: {e}")
        return None

def get_semantic_scholar_tool_for_agent():
    """
    Initializes the Semantic Scholar tool.
    Returns a list containing the tool, suitable for an agent.
    """
    try:
        ss_reader = SemanticScholarReader()
        tool = FunctionTool.from_defaults(
            fn=lambda query: ss_reader.load_data(query=query, limit=5), # Load 5 papers
            name="semantic_scholar_search",
            description="Searches Semantic Scholar for academic papers based on a query.",
        )
        return tool
    except Exception as e:
        print(f"Error initializing Semantic Scholar Tool: {e}")
        return None

def get_web_scraper_tool_for_agent():
    """
    Initializes the Web Scraper tool.
    Returns a list containing the tool, suitable for an agent.
    """
    try:
        loader = SimpleWebPageReader(html_to_text=True)
        tool = FunctionTool.from_defaults(
            fn=lambda url: loader.load_data(urls=[url]),
            name="web_scraper",
            description="Scrapes textual content from a given URL. This can be an HTML webpage or a direct link to a PDF document. Expects a single URL as input.",
        )
        return tool
    except Exception as e:
        print(f"Error initializing Web Scraper Tool: {e}")
        return None

def get_rag_tool_for_agent():
    """Initializes the RAG query tool by loading the SimpleVectorStore from Hugging Face Hub."""
    
    hf_persist_path = f"datasets/{HF_DATASET_ID}/{HF_VECTOR_STORE_SUBDIR}"
    print(f"Attempting to load RAG index from Hugging Face Hub: {hf_persist_path}")

    try:
        hf_token = os.getenv("HF_TOKEN")
        if not hf_token:
            print("Warning: HF_TOKEN environment variable not set. Make sure you are logged in via `huggingface-cli login` or have set HF_TOKEN for read access to the Hugging Face Dataset.")
        
        hf_fs = HfFileSystem(token=hf_token)

        if not Settings.embed_model:
            print("Error: Settings.embed_model not configured. Cannot load RAG index.")
            raise ValueError("Settings.embed_model is not set.")
        if not Settings.llm:
            print("Error: Settings.llm not configured. Cannot create RAG query engine.")
            raise ValueError("Settings.llm is not set.")

        print("Loading index from Hugging Face storage...")
        storage_context = StorageContext.from_defaults(persist_dir=hf_persist_path, fs=hf_fs)
        
        index = load_index_from_storage(storage_context, embed_model=Settings.embed_model)
        print(f"Successfully loaded index from Hugging Face Hub: {hf_persist_path}")

        query_engine = index.as_query_engine(llm=Settings.llm)
        print("RAG query engine created.")

        def execute_rag_query(input: str):
                 """Executes a query against the RAG engine and returns the text response."""
                 try:
                     response_obj = query_engine.query(input)
                     text_response = str(response_obj.response)

                     sources_info_parts = []
                     citation_counter = 1
                     assigned_pdf_citations = {}

                     if response_obj.source_nodes:
                         for source_node in response_obj.source_nodes:
                             metadata = source_node.node.metadata
                             node_text_snippet = source_node.node.get_text()[:100]

                             if 'file_path' in metadata:
                                 file_path = metadata['file_path']
                                 file_name = os.path.basename(file_path)
                                 
                                 current_citation_number = None
                                 if file_path not in assigned_pdf_citations:
                                     assigned_pdf_citations[file_path] = citation_counter
                                     current_citation_number = citation_counter
                                     citation_counter += 1
                                 else:
                                     current_citation_number = assigned_pdf_citations[file_path]
                                 
                                 source_data = {
                                     "type": "pdf", 
                                     "name": file_name, 
                                     "path": file_path, 
                                     "snippet": node_text_snippet + "...",
                                     "citation_number": current_citation_number
                                 }
                                 sources_info_parts.append(f"---RAG_SOURCE---{json.dumps(source_data)}")
                             elif 'url' in metadata:
                                 url = metadata['url']
                                 title = metadata.get('title', url)
                                 source_data = {"type": "web", "url": url, "title": title, "snippet": node_text_snippet + "..."}
                                 sources_info_parts.append(f"---RAG_SOURCE---{json.dumps(source_data)}")

                     if sources_info_parts:
                         return text_response + "\n" + "\n".join(sources_info_parts)
                     else:
                         return text_response

                 except Exception as e:
                     print(f"Error during RAG query execution: {e}")
                     return f"Error querying the knowledge base: {e}"

        return FunctionTool.from_defaults(
                 fn=execute_rag_query,
                 name="rag_dissertation_retriever",
                 description=(
                    f"Retrieves relevant information from the dissertation knowledge base (persisted on Hugging Face at '{HF_DATASET_ID}/{HF_VECTOR_STORE_SUBDIR}'). "
                    "Use this for specific institutional knowledge or previously saved research. "
                    "The tool's output will include the textual answer and may be followed by structured references "
                    "(e.g., to PDF files or web URLs) using '---RAG_SOURCE---' markers. "
                    "For PDF sources, the structured reference will include a 'citation_number'. "
                    "When you use information from a PDF source in your response, you MUST append its citation number "
                    "in brackets (e.g., '[1]', '[2]') to the relevant sentence or claim. "
                    "The query to the knowledge base should be provided as the 'input' string argument."
                 ),
             )

    except Exception as e:
        error_message = f"Error initializing or loading RAG tool from Hugging Face ({HF_DATASET_ID}/{HF_VECTOR_STORE_SUBDIR}): {e}"
        print(error_message)
        return FunctionTool.from_defaults(
            fn=lambda *args, msg=error_message, **kwargs: msg,
            name="rag_dissertation_retriever",
            description=f"The dissertation knowledge base (from Hugging Face: {HF_DATASET_ID}/{HF_VECTOR_STORE_SUBDIR}) is currently unavailable due to an error during initialization."
        )


# --- Tool Collections for Specialized Agents ---

def get_search_tools():
    """Initializes and returns a list of search-related tools."""
    tools = []
    ddg_tool = get_duckduckgo_tool()
    tavily_tool = get_tavily_tool()
    wiki_tool = get_wikipedia_tool()

    if ddg_tool: tools.append(ddg_tool)
    if tavily_tool: tools.append(tavily_tool)
    if wiki_tool: tools.append(wiki_tool)
    
    print(f"Initialized {len(tools)} search tools.")
    return tools

# --- Code Interpreter Tool Setup ---

def get_coder_tools():
    """
    Initializes the Code Interpreter tool, configured to use the shared workspace.
    Returns the original tool spec's tool list.
    """
    try:
        # Instantiate CodeInterpreterToolSpec without arguments as per error message
        code_spec = CodeInterpreterToolSpec()

        # Access the underlying CodeInterpreter instance and set its work_dir
        if hasattr(code_spec, '_code_interpreter') and isinstance(code_spec._code_interpreter, CodeInterpreter):
            code_spec._code_interpreter.work_dir = UI_ACCESSIBLE_WORKSPACE
            print(f"Code interpreter work_dir set to: {code_spec._code_interpreter.work_dir}")
        else:
            print("Warning: Could not access or set work_dir on CodeInterpreter instance. Files may be saved to a temporary location.")

        original_tools = code_spec.to_tool_list()

        if not original_tools:
            print("Warning: CodeInterpreterToolSpec returned no tools.")
            return []

        print(f"Initialized Code Interpreter Tool(s) for Coder Agent: {[t.metadata.name for t in original_tools]}")
        return original_tools
    except Exception as e:
        print(f"Error initializing Code Interpreter Tool for Coder Agent: {e}. Code execution will be unavailable.")
        return []
